# f=open("sample.txt","w")
# f.write("learn python")
# f.close()


# f=open(r"C:\Users\NETCOM\Desktop\python\data.txt","w")
# f.close()


# f=open("sample.txt","r")
# print(f.read())
# f.close()

# f=open("sample.txt","r")
# print(f.readline())
# print(f.readline())
# print(f.readline())
# print(f.readlines())
# f.write("learn javascript\n")
# f=open("sample1.txt","x")
# f.close()

# f=open("images.jpg", "rb")
# print(f.read())
# print(f.read(20))
# f.close()

# p=open("sample.txt","r+")
# print(p.read())
# p.write("goodbye\n")
# print(p.read())
# p.close()
# p=open("sample.txt","r+")
# print(p.read())
# p.close
# p=open("sample.txt","w+")
# print(p.read())
# p.write("goodbye\n")
# print(p.read())
# p.close()
# p=open("sample.txt","a+")
# print(p.read())
# p.write("goodbye\n")
# print(p.read())
# p.close()
# f=open("sample.txt","w")
# f.write("welcome to python")
# print(f.name)
# print(f.mode)
# print(f.closed)
# f.close()
# print(f.closed)
# f=open("sample.txt","w")
# f.writelines(["welcome to python\n","learn python\n","goodbye\n","rahul\n","hello 'world'"])
# f.close()
# f=open("sample.txt","w")
# f.write("welcome to python")
# f.close()

# with open("sample.txt","w") as f:
#     f.write("hello")